config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    resources :comments
  end
    # get 'posts/:id', to:'posts#show'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user


    validates :content, presence: true, length: {minimum: 5}

  
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :content, presence: true, length: {minimum: 5}
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :registerable, :confirmable
  
  
  validates :email, presence: true
  validates :password, presence: true
  validates_associated :posts, :comments
  

  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:index]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    # before_action :set_comment, only: %i[ show edit update destroy ]

    def index
    end

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(comment_params.merge(user_id: current_user.id, post_id: params[:post_id]))
        
        if @comment.save
            redirect_to post_url(@post), notice: "Comment has been added"
        else
            redirect_to post_url(@post)
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to posts_path(@post)
    end

    private

    def set_comment
        @comment = Comment.find(params[:id])
        rescue ActiveRecord::RecordNotFound
          redirect_to posts_path, notice: "NO comments"
      end

    def comment_params
        params.require(:comment).permit(:content)
      end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
    private
    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource) # In case you want to sign in the user
      root_path

    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: %i[ show edit update destroy ]
    
    def index
        @posts = Post.all.order('created_at DESC')
    end

    def new
        @post = Post.new
    end

    def show
    end

    def create
        @post = Post.new(post_params.merge(user_id: current_user.id))
    
          if @post.save
            redirect_to posts_url, notice: "Post was successfully created."
          else
            render :new, status: :unprocessable_entity 
          end

    end

    def update
      if @post.update(post_params) 
      redirect_to post_url(@post), notice: "Post has been updated"
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def edit
        
    end

    def destroy
        @post.destroy
        redirect_to posts_url(@post), "Post has been deleted"
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def find_post
      @post = Post.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to posts_path, notice: "Post no found"
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <%= comment.content %>
        </p>
      </div>
    </div>
    <% if @post.user == current_user%>
     <%= link_to 'Delete', [comment.post, comment],
                  data: {turbo_method: :delete, turbo_confirm: "Do you want to delete the comment?"}, class: "button is-light"%>
    <% end %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |form| %>
  <div class="field">
    <label class="label"><%= form.label :Comment %></label>
    <div class="control">
      <%= form.text_area :content, class:"textarea", type:"text", placeholder:"Write Your Comments" %>
    </div>
  </div>
  <%= form.button :submit, 'Create comment', class: "button is-dark" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>WebblogWeek4</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    
    <section>

        <nav class="navbar has-shadow">
          <div class="container">
            <div class="navbar-brand">
            <div class="navbar-item">
              <%= link_to "Web Blog", root_url, class:"navbar-item title is-5"%>
            </div> 
             <span class="navbar-burger" data-target="navbarMenuHeroA">
                <span></span>
                <span></span>
                <span></span>
              </span>
            </div>
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <%= link_to "Create Blog", new_post_path,class:"navbar-item is-active" %>
                <% if user_signed_in? %>
                  <span class="navbar-item">
                  <%= link_to 'Account', edit_user_registration_path, class:"button is-light is-inverted" %>
                  </span>
                  <span class="navbar-item">
                    <%= link_to 'Sign out', destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "user sign out"}, class:"button is-light is-inverted" %>
                  </span>
                <% else %>
                  <span class="navbar-item">
                    <%= link_to "Sign Up", new_user_registration_path, class:"button is-light is-inverted"%>
                  <span class="navbar-item">
                    <%= link_to "Sign In", user_session_path, class:"button is-light is-inverted" %>
                  </span>
                <% end %>
              </div>
            </div>
          </div>
        </nav>
        <div class="container mt-4">
          <% if notice%>
            <div class="notification is-primary">
              <button class="delete"></button>
                <%= notice%>
              </div>
              
          <% end %>
        <div>


        <div class="container mt-4">
          <%= yield %>
        </div>
    </section>
    
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
  <div class="card">
    <div class="card-content">
      <div class="content"> 
        <%= form_for @post do |form| %>
          <% if @post.errors.any? %>
            <h2>The following errors prevented the post from saving:</h2>
            <ul>
            <% @post.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
            <% end %>
            </ul>
          <% end %>
          <div class="field">
            <label class="label"><%= form.label :title %></label>
            <div class="control">
              <%= form.text_field :title, class:"input", type:"text", placeholder:"Blog Title" %>
            </div>
          </div>
            <div class="field">
            <label class="label"><%= form.label :content %></label>
            <div class="control">
              <%= form.text_area :content, class:"textarea", type:"textarea", placeholder:"Write your blog" %>
            </div>
          </div>

          <p>
            <%= form.submit class:"button is-dark"%>
          </p>
        <% end %>
      
      </div> 
        <%= link_to "Back to posts", posts_path, class:"button"%>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "edit post" %>
<div class="section">
    <div class="title has-text-centered">
        Edit Blog
    </div>
    <%= render 'form', post: @post%>
    
</div>

app/views/posts/index.html.erb
<% content_for :page_title, "index"%>

<div class="section">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="card mb-4">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4"><%= link_to post.title, post  %></p>
            </div>
            <p class="date">
              <%= post.created_at.strftime('%B, %d, %Y')%>
            </p>
          </div>
          
          <div class="comment-count">
            <span class="tag is-rounded"><%= post.comments.count %> comments</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a new post" %>
<div class="section">
    <div class="title has-text-centered">
        Create Blog
    </div>
    <%= render 'form', post: @post%>
    
</div>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
    <div class="container">
        <nav class="level">
          <!-- Left side -->
          <div class="level-left">
            <div >
              <h1 class="title"> <%= @post.title %></h1>
              <p class="date">
                updated at <%= @post.updated_at.in_time_zone("Jakarta").strftime('%H:%M, %Y-%m-%d')%>
              </p>           
            </div> 
          </div>
          <!-- Right side -->
          <div class="level-right">
              <% if @post.user == current_user%>
                <p class="level-item">
                  <%= link_to "Edit", edit_post_path(@post), class:"button is-dark" %>
                </p>
                <p class="level-item">
                  <%= link_to "Delete", @posts, data: {turbo_method: :delete, turbo_confirm: "DO want to delete it?"}, class:"button is-light" %>
                </p>
                
              <% end %>
              <%= link_to "Back to posts", posts_path, class:"button is dark"%>
          </div>
        </nav>
        <hr/>

        <div class="content is-justify-content-center">
            <%= @post.content %>
        </div>
    </div>
</section>

<section class="section comments">
    <div class="container">
        <h2 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h2>
        <%= render @post.comments %>
        <div class="comment-form">
            <hr />
            <h3 class="subtitle is-3">Create comments</h3>
             <%= render 'comments/form' %>
        </div>
    </div>
</section>